version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: todo-app

  app:
    build: .
    container_name: todo-app
    restart: always
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://root:example@mongo:27017/todo-app?authSource=admin
      JWT_SECRET: your_jwt_secret_key
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  mongo-data: